"""
model.py
--------
This file defines our database TABLE for categories.

In SQLAlchemy, a Python class = a database table.
Each class attribute = a column in that table.

Our Category table stores everything the CategoryManager used to keep in memory:
- The numeric ID of the category
- Its human-readable name (e.g. "Football News")
- The domain it belongs to (e.g. "sports", "tech")
- How many items have been assigned to it
- The centroid (average embedding vector), stored as raw bytes
- A JSON list of sample texts seen so far
"""

import json
import pickle
import numpy as np
from sqlalchemy import Column, Integer, String, LargeBinary, Text
from app.db.database import Base


class Category(Base):
    """
    Represents one category row in the `categories` table.
    """

    # The name of the table in the SQLite file
    __tablename__ = "categories"

    # Primary key — SQLite auto-increments this for us
    id = Column(Integer, primary_key=True, index=True)

    # Human-readable name generated by the AI (e.g. "Cricket Matches")
    # nullable=True means it can be empty before we have enough data
    name = Column(String, nullable=True)

    # Which broad topic this category belongs to (e.g. "sports", "tech")
    domain = Column(String, nullable=False)

    # How many items have been assigned to this category
    count = Column(Integer, default=0)

    # The centroid vector — stored as binary (bytes) using pickle.
    # NumPy arrays can't be stored directly in SQL, so we serialize them.
    centroid = Column(LargeBinary, nullable=False)

    # A JSON-encoded list of sample texts, e.g. '["Messi scores", "Ronaldo header"]'
    texts = Column(Text, default="[]")

    # -------------------------------------------------------------------------
    # Helper methods to convert between Python types and DB-storable types
    # -------------------------------------------------------------------------

    def get_centroid(self) -> np.ndarray:
        """Deserialize the centroid bytes back into a NumPy array."""
        return pickle.loads(self.centroid)

    def set_centroid(self, array: np.ndarray):
        """Serialize a NumPy array into bytes for storage."""
        self.centroid = pickle.dumps(array)

    def get_texts(self) -> list:
        """Deserialize the texts JSON string back into a Python list."""
        return json.loads(self.texts)

    def set_texts(self, texts: list):
        """Serialize a Python list into a JSON string for storage."""
        self.texts = json.dumps(texts)
